# Copyright Siemens AG 2020, anupam.ghosh@siemens.com, gaurav.mishra@siemens.com
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

stages:
  - license

license_check:
  stage: license
  image: fossology/fossology:scanner
  script:
    - /bin/fossologyscanner nomos ojo
  only: [merge_requests]
  artifacts:
    paths:
    - results
    expire_in: 1 week
    when: on_failure

copyright_check:
  stage: license
  image: fossology/fossology:scanner
  script:
    - /bin/fossologyscanner copyright keyword
  only: [merge_requests]
  artifacts:
    paths:
    - results
    expire_in: 1 week
    when: on_failure

repo_license_scan:
  stage: license
  image: fossology/fossology:scanner
  script:
    - /bin/fossologyscanner repo nomos ojo
  only: [tags]
  artifacts:
    paths:
    - results
    expire_in: 1 week
    when: on_failure

repo_copyright_check:
  stage: license
  image: fossology/fossology:scanner
  script:
    - /bin/fossologyscanner copyright keyword repo
  only: [tags]
  artifacts:
    paths:
    - results
    expire_in: 1 week
    when: on_failure
